<div class="blocglobal">
	<?php if (count($nosEntrees) == 0) {
		echo "<p>Aucune entrée n'est dipsonible</p>";
	} else {
		foreach ($nosEntrees as $value): ?>
		<div class="produitsBloc">
			<img id="<?= $value['Id']?>" src="<?= $wwwUrl."/images/meals/".$value['Photo']?>" alt="<?= $value['Photo']?>" >
			<p class="titre"><?= $value['Name'] ?></p>
			<p class="description"><?= $value['Description'] ?></p>
			<p class="prix">Prix: <?= $value['SalePrice']?> EUR</p>
			<form class="" action="<?= $requestUrl ?>" method="post">
				<p>
					<label>Quantité</label>
					<input type="number" name="orderQuantity" value="1">
				</p>
				<input type="hidden" name="mealId" value="<?= $value['Id']?>">

				<input type="hidden" name="mealName" value="<?= $value['Name']?>">
				<input type="hidden" name="mealDescription" value="<?= $value['Description']?>">
				<input type="hidden" name="mealPhoto" value="<?= $value['Photo']?>">
				<input type="hidden" name="mealSalePrice" value="<?= $value['SalePrice']?>">
				<input type="submit" name="" value="Ajouter au panier">
			</form>
		</div>
	<?php endforeach ?>
<?php } ?>
</div>
