<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>3WA Restaurant</title>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize-3.0.3.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/font-awesome-4.3.0.min.css">

    <!-- Feuilles de styles de l'application -->
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/3wa-resto.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-button.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-form.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/ui-table.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Oleo+Script+Swash+Caps|Karla">
	<link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">

    <!-- Librairie jQuery -->
    <script src="http://code.jquery.com/jquery-2.1.0.min.js"></script>

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
    <script src="<?= $wwwUrl ?>/js/ajax.js"></script>
    <script src="<?= $wwwUrl ?>/js/main.js"></script>
</head>
<body>

<!-- En-tête commune -->
<header>
    <h1>
        <a href="<?= $requestUrl ?>">
            <img src="<?= $wwwUrl ?>/images/logo.gif" height="63" width="57" alt="3WA Restaurant">Restaurant - Made In America !
        </a>
    </h1>
    <!--bouton panier  -->
	<a href="<?= $requestUrl ?>/panier">Panier
        <span>
            <?php
            new UserSession();
            if (count($_SESSION['panier']) > 0) {
                echo (new PanierModel(new database()))->totalCommandes();
            } ?>
        </span>
        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
    </a>
</header>

<!-- Interface utilisateur -->
<nav class="user-interface">
    <ul class="">
        <li><a href="<?= $requestUrl ?>">Accueil</a></li>
		<li class="notreCarte"><a href="#">Notre catre</a>
			<ul class="nosOffres hideMenu">
				<li><a href="<?= $requestUrl ?>/entree">Entrées</a></li>
				<li><a href="<?= $requestUrl ?>/plats">Plats</a></li>
				<li><a href="<?= $requestUrl ?>/desserts">Désserts</a></li>
				<li><a href="<?= $requestUrl ?>/boissons">Boissons</a></li>
			</ul>
		</li>
		<li class="booking"><a href="">Réserver une table</a>
			<ul class="bookingAction hideMenu">
				<li><a href="<?= $requestUrl ?>/booking">Faire une réservation</a></li>
				<li><a href="">Gérer mes réservations</a></li>
			</ul>
		</li>
		<li><a href="<?= $requestUrl ?>/customer">Se connecter</a></li>
    </ul>
</nav>

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun -->
<footer>
    <ul class="link-list">
        <li><img src="<?= $wwwUrl ?>/images/payment/visa.png" alt="Visa"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/mastercard.png" alt="MasterCard"></li>
        <li><img src="<?= $wwwUrl ?>/images/payment/paypal.png" alt="PayPal"></li>
    </ul>
    <small>Réalisé avec <i class="fa fa-heart"></i>&nbsp; par les élèves de la 3W Academy</small>
    <a href="<?= $requestUrl ?>/employees/login">Espace admin</a>
</footer>

<!-- Code principal JavaScript de l'application -->
<script src="<?= $wwwUrl ?>/js/main.js"></script>

</body>
</html>
