<div class="">
	<?php if (count($nosBoissons) == 0) {
		echo "<p>Aucune entrée n'est dipsonible</p>";
	} else {
		foreach ($nosBoissons as $value): ?>
			<img id="<?php $value['Id']?>" src="<?= $wwwUrl."/images/meals/".$value['Photo']?>" alt="<?= $value['Photo']?>" >
			<p><?= $value['Description'] ?></p>
			<p><?php $value['SalePrice']?></p>
			<form class="" action="" method="post">
				<p>
					<label>Quantité</label>
					<input type="number" name="orderQuatity" value="1">
				</p>
				<input type="hidden" name="mealId" value="<?php $value['Id']?>">
				<input type="hidden" name=mealName"" value="<?php $value['Name']?>">
				<input type="hidden" name="mealPhoto" value="<?php $value['Photo']?>">
				<input type="hidden" name="mealSalePrice" value="<?php $value['SalePrice']?>">
				<input type="submit" name="" value="Ajouter au panier">
			</form>
	<?php endforeach ?>
<?php } ?>
</div>
