
<!-- Formulaire de réservation à remplir par le client -->
<form class="" action="http://localhost/cletusResto/resto_3wa/www/index.php/booking" method="post">
    <p>
        <input type="hidden" name="" value="">
    </p>
    <p>
        <label for="customerName">Nom</label>
        <input type="text" id="customerName" name="customerName" value="<?= $customerName ?>">
    </p>
    <p>
        <label for="customerName">Téléphone</label>
        <input type="text" id="customerPhone" name="customerPhone" value="<?= $customerPhone ?>">
    </p>
    <p>
        <label for="bookingDate">Date</label>
        <input type="date" id="bookingDate" name="bookingDate" value="<?= $bookingDate ?>">
    </p>
    <p>
        <label for="bookingHour">Heure</label>
        <select id="bookingHour" class="" name="bookingHour">
            <<option value="">Heure de réservation</option>
            <!-- affichage de façon dynamique de la liste des horaires -->
            <?php foreach ($hoursList as $value) { ?>
                    <option value="<?= $value['Id'] ?>"><?= $value['Hours'] ?></option>
            <?php } ?>
        </select><span id="alertMessage"></span>
    </p>
    <p>
        <label for="bookingPlace">Nombre de place</label>
        <input type="text" id="bookingPlace" name="placeNumber" value="<?= $placeNumber ?>">
    </p>

    <p>
        <input type="submit" id="btn-submit" name="btn-submit" value="Réserver">
        <!-- Message d'alerte lorsque tous les champs du formulaires ne sont pas renseignés -->
        <span id="errorForm"></span> <span class="flashBag"><?php
        if ($errorForm->hasMessages()){
            foreach ($errorForm->fetchMessages() as $value) {
                echo $value;
            }
        }?>
    </span>
</form>
